### ISSUE TITLE
python3 无法安装

### ISSUE THREAD

**Issue by fy0** [mozillazg/baidu-pcs-python-sdk#7]
windows下，是编码问题。

Install packages failed: Error occurred when installing package baidupcs. 

The following command was executed:

packaging_tool.py install --build-dir C:\Users\yu\AppData\Local\Temp\pycharm-packaging5188425833334793363.tmp baidupcs

The error output of the command:

DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking baidupcs
  Downloading baidupcs-0.3.1.zip
  Running setup.py (path:C:\Users\yu\AppData\Local\Temp\pycharm-packaging5188425833334793363.tmp\baidupcs\setup.py) egg_info for package baidupcs
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\yu\AppData\Local\Temp\pycharm-packaging5188425833334793363.tmp\baidupcs\setup.py", line 37, in <module>
        long_description=long_description(),
      File "C:\Users\yu\AppData\Local\Temp\pycharm-packaging5188425833334793363.tmp\baidupcs\setup.py", line 31, in long_description
        return open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 76: illegal multibyte sequence
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\yu\AppData\Local\Temp\pycharm-packaging5188425833334793363.tmp\baidupcs\setup.py", line 37, in <module>

```
long_description=long_description(),
```

  File "C:\Users\yu\AppData\Local\Temp\pycharm-packaging5188425833334793363.tmp\baidupcs\setup.py", line 31, in long_description

```
return open('README.rst').read() + '\n\n' + open('CHANGELOG.rst').read()
```

UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 76: illegal multibyte sequence

**Comment by mozillazg** [comment]
Closed via 3f74bbc
